import React, { useState } from 'react';
import { FileText, Sparkles, CheckSquare, TrendingUp, Download, Copy, Check } from 'lucide-react';
import { Appointment } from '../../types';

interface TranscriptMessage {
  sessionId: string;
  participantName: string;
  text: string;
  timestamp: number;
  isFinal: boolean;
}

interface PostMeetingTranscriptProps {
  appointment: Appointment;
  liveMessages: TranscriptMessage[];
  lawyerName: string;
  clientName: string;
  onClose: () => void;
  onGenerateAISummary: () => void;
}

const PostMeetingTranscript: React.FC<PostMeetingTranscriptProps> = ({
  appointment,
  liveMessages,
  lawyerName,
  clientName,
  onClose,
  onGenerateAISummary,
}) => {
  const [activeTab, setActiveTab] = useState<'transcript' | 'ai'>('transcript');
  const [copied, setCopied] = useState(false);

  // Combine live messages into full transcript
  const fullTranscript = liveMessages
    .filter(msg => msg.isFinal)
    .map(msg => `[${msg.participantName}] ${msg.text}`)
    .join('\n\n');

  const handleCopy = () => {
    navigator.clipboard.writeText(fullTranscript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([fullTranscript], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `transcript-${appointment.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Mock AI features (will be generated by Gemini)
  const aiFeatures = {
    summary: appointment.summary || 'Génération en cours...',
    keyPoints: [
      'Discussion sur la problématique juridique du client',
      'Analyse des options légales disponibles',
      'Plan d\'action établi avec échéances',
    ],
    actionItems: [
      { text: 'Préparer les documents nécessaires', assignee: 'Client', deadline: '3 jours' },
      { text: 'Rédiger la lettre de mise en demeure', assignee: 'Avocat', deadline: '5 jours' },
      { text: 'Fixer le prochain rendez-vous', assignee: 'Les deux', deadline: '1 semaine' },
    ],
    sentiment: 'positive' as 'positive' | 'neutral' | 'negative',
  };

  return (
    <div className="fixed inset-0 bg-slate-900/95 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-slate-800 rounded-2xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-hidden border border-slate-700">
        {/* Header */}
        <div className="px-6 py-4 bg-slate-900 border-b border-slate-700 flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold text-white mb-1">Transcription de la consultation</h2>
            <p className="text-sm text-slate-400">
              {lawyerName} • {clientName} • {new Date(appointment.date).toLocaleDateString('fr-FR')}
            </p>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white transition-colors"
          >
            <span className="text-2xl">×</span>
          </button>
        </div>

        {/* Tabs */}
        <div className="px-6 pt-4 flex gap-2 border-b border-slate-700">
          <button
            onClick={() => setActiveTab('transcript')}
            className={`px-4 py-2 rounded-t-lg font-medium transition-colors ${activeTab === 'transcript'
                ? 'bg-slate-700 text-white'
                : 'text-slate-400 hover:text-white'
              }`}
          >
            <FileText className="w-4 h-4 inline mr-2" />
            Transcription complète
          </button>
          <button
            onClick={() => setActiveTab('ai')}
            className={`px-4 py-2 rounded-t-lg font-medium transition-colors ${activeTab === 'ai'
                ? 'bg-slate-700 text-white'
                : 'text-slate-400 hover:text-white'
              }`}
          >
            <Sparkles className="w-4 h-4 inline mr-2" />
            Analyse IA
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto max-h-[60vh]">
          {activeTab === 'transcript' ? (
            <div>
              {/* Actions */}
              <div className="flex gap-2 mb-4">
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-2 px-3 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg text-sm transition-colors"
                >
                  {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                  {copied ? 'Copié!' : 'Copier'}
                </button>
                <button
                  onClick={handleDownload}
                  className="flex items-center gap-2 px-3 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg text-sm transition-colors"
                >
                  <Download className="w-4 h-4" />
                  Télécharger
                </button>
              </div>

              {/* Transcript */}
              <div className="bg-slate-900 rounded-lg p-4 space-y-4">
                {liveMessages.filter(msg => msg.isFinal).length === 0 ? (
                  <p className="text-slate-400 text-center py-8">
                    Aucune transcription disponible. La consultation était peut-être trop courte.
                  </p>
                ) : (
                  liveMessages
                    .filter(msg => msg.isFinal)
                    .map((msg, index) => (
                      <div key={index} className="border-l-2 border-brand-DEFAULT pl-4 py-2">
                        <div className="flex items-center gap-2 mb-1">
                          <span className="font-medium text-brand-DEFAULT text-sm">
                            {msg.participantName}
                          </span>
                          <span className="text-xs text-slate-500">
                            {new Date(msg.timestamp).toLocaleTimeString('fr-FR')}
                          </span>
                        </div>
                        <p className="text-white leading-relaxed">{msg.text}</p>
                      </div>
                    ))
                )}
              </div>
            </div>
          ) : (
            <div className="space-y-6">
              {/* AI Summary */}
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <Sparkles className="w-5 h-5 text-brand-DEFAULT" />
                  <h3 className="text-lg font-semibold text-white">Résumé IA</h3>
                </div>
                <div className="bg-slate-900 rounded-lg p-4">
                  {appointment.summary ? (
                    <p className="text-white leading-relaxed whitespace-pre-wrap">
                      {appointment.summary}
                    </p>
                  ) : (
                    <div className="text-center py-4">
                      <button
                        onClick={onGenerateAISummary}
                        className="px-4 py-2 bg-brand-DEFAULT hover:bg-brand-dark text-white rounded-lg font-medium transition-colors"
                      >
                        Générer le résumé IA
                      </button>
                    </div>
                  )}
                </div>
              </div>

              {/* Key Points */}
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <TrendingUp className="w-5 h-5 text-green-400" />
                  <h3 className="text-lg font-semibold text-white">Points clés</h3>
                </div>
                <div className="bg-slate-900 rounded-lg p-4 space-y-2">
                  {aiFeatures.keyPoints.map((point, index) => (
                    <div key={index} className="flex items-start gap-2">
                      <div className="w-1.5 h-1.5 bg-brand-DEFAULT rounded-full mt-2" />
                      <p className="text-white flex-1">{point}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Action Items */}
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <CheckSquare className="w-5 h-5 text-blue-400" />
                  <h3 className="text-lg font-semibold text-white">Actions à suivre</h3>
                </div>
                <div className="bg-slate-900 rounded-lg p-4 space-y-3">
                  {aiFeatures.actionItems.map((item, index) => (
                    <div
                      key={index}
                      className="flex items-start gap-3 p-3 bg-slate-800 rounded-lg"
                    >
                      <input
                        type="checkbox"
                        className="mt-1 w-4 h-4 text-brand-DEFAULT rounded focus:ring-brand-DEFAULT"
                      />
                      <div className="flex-1">
                        <p className="text-white font-medium mb-1">{item.text}</p>
                        <div className="flex items-center gap-3 text-sm text-slate-400">
                          <span>👤 {item.assignee}</span>
                          <span>⏰ {item.deadline}</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 bg-slate-900 border-t border-slate-700 flex items-center justify-between">
          <p className="text-sm text-slate-400">
            {liveMessages.filter(msg => msg.isFinal).length} messages • Durée totale enregistrée
          </p>
          <button
            onClick={onClose}
            className="px-4 py-2 bg-brand-DEFAULT hover:bg-brand-dark text-white rounded-lg font-medium transition-colors"
          >
            Fermer
          </button>
        </div>
      </div>
    </div>
  );
};

export default PostMeetingTranscript;
